### ISSUE TITLE
attack.sh and ipv4

### ISSUE THREAD

**Issue by mxalk** [seclab-ucr/SADDNS2.0#1]
Hello authors,
Nice job on your publications.

In README you mention attack.sh script but it seems nowhere to be found.
Could you possibly upload the sample attack script?

Also i cant seem to run in pure ipv4. Is it supported?

Many thanks

**Comment by mkyybx** [comment]
Hi mxalk,
    I removed attack.sh-related stuff in readme.md. It was highly optimized for my attack (e.g., contains aws commands) and therefore it may not be suitable for others to use. 
    For IPv4, please modify these consts accordingly: https://github.com/seclab-ucr/SADDNS2.0/blob/main/src/ucr.edu/SADDNS2.0/main.go#L78 and you are good to go. Also ignore the prompts in arguments to put IPv6 addresses and put IPv4-related arguments instead.
    Let me know about other questions / thoughts.
