### ISSUE TITLE
Doubt in running the files

### ISSUE THREAD

**Issue by Abhinav-Singhal-8130** [seclab-ucr/SADDNS2.0#2]
Hi authors,
Thank you for providing the implementation of the attack; However, I am new to this field and had a few doubts related to the setup. I wish to conduct the attack and see the results by using 2-3 separate VMs on linux.

As you have mentioned, in the dns_query.sh file, the command to execute is:
./dns_query.sh [NS IP] [Resolver IP(spoofed as source IP)] space-separated-domain... (e.g. www google com)

How can I get the NS IP and Resolver IP? and is the space-separated-domain the victim's domain whose actual ip in the dns record will be switched to that of the attacker's domain ip?

You have also mentioned that we will need: 
The resolver to poison (victim resolver)
The domain to poison (victim domain)

How do I setup the victim resolver and victim domain on Ubuntu VMs? Please help as I am kind of clueless regarding the setup of the attack.

Hoping for a quick response.
Thank you.

**Comment by mkyybx** [comment]
Hi Abhinav,
    Your understanding is basically right. Please refer to our paper for more attack details and for implementation its setup should be similar to ordinary cache poisoning attacks.
